name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests
        run: go test ./... -cover

      # - name: Set up Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: "1.23.0"

      - name: Force to succeed
        run: (exit 0)

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Run style check
        run: test -z $(go fmt ./...)

      - name: Force to succeed
        run: (exit 0)
